### ISSUE TITLE
Detects barcode and the app closes

### ISSUE THREAD

**Issue by mezalejandro** [adamweeks/ion-scanner#1]
Hi Adam,
your tutorial is great!
But i have an error, when execute the app, press the button Scan, read the barcode show the message "Text found" and closes the app.

Please can you help me,
Thanks

**Comment by adamweeks** [comment]
Hey, I haven't checked out this project in a while. There might be some cordova updates that need to be done. I'll try to look at it in the next couple of weeks. If you figure it out, PRs are welcomed :)
