### ISSUE TITLE
missing steps - iritating !!

### ISSUE THREAD

**Issue by thompsk** [adamweeks/ion-scanner#2]
I was really happy to have found your blogpost detailing (or so I thought) how to put together a barcode scanner for ionic. Having very carefully followed your plain and easy to follow steps to build this app I had to spend the next 3 hours trying to figure out why it wasn't working only to find out that you decided to skip some of the steps (sadly critical ones) likely for brevity but without informing the reader that this is what you were doing.

So the reader continues, trusting your words only to dig themselves into a hole.

Could I suggest that if you decide to miss out steps all you have to do is just mention that to the reader - which would be much more helpful than keeping it quiet -

**Comment by adamweeks** [comment]
Not sure if you noticed, but this repo is a couple years old now. I'm sure some of the process has changed. If there are some missing steps, I'd gladly welcome a PR to update the document. Might I suggest something like:

> Hi, I just came across this repo and found that since the time of writing, some of the steps have changed. In order to get it working, you now have to do X and Y. I've submitted a PR with those changes documented. Thanks for putting this out there, it helped me get my project up and running faster than starting from scratch!
