### ISSUE TITLE
Custom UI for scanner and prompt message?

### ISSUE THREAD

**Issue by jramgit** [adamweeks/ion-scanner#3]
Thank for this! It saves me a lot of time.

I'd like to create a dotted border for the viewfinder and add a new text on top of the view finder. Also change the text of the default message. Both for Android and iOS.

I'd like to customize the UI for the scanning page as I mentioned above. Can you point in the right direction on how to do this ?

**Comment by adamweeks** [comment]
It looks like you would need to modify the actual scanner plugin being used, probably creating a fork off of https://github.com/phonegap/phonegap-plugin-barcodescanner
